/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"
	"encoding/json"
	"fmt"

	apirbacv1alpha1 "k8s.io/api/rbac/v1alpha1"
	apismetav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	apimachinerypkglabels "k8s.io/apimachinery/pkg/labels"
	pkgruntimeschema "k8s.io/apimachinery/pkg/runtime/schema"
	apimachinerypkgtypes "k8s.io/apimachinery/pkg/types"
	apimachinerypkgwatch "k8s.io/apimachinery/pkg/watch"
	applyconfigurationsrbacv1alpha1 "k8s.io/client-go/applyconfigurations/rbac/v1alpha1"
	clientgotesting "k8s.io/client-go/testing"
)

// FakeRoles implements RoleInterface
type FakeRoles struct {
	Fake *FakeRbacV1alpha1
	ns   string
}

var rolesResource = pkgruntimeschema.GroupVersionResource{Group: "rbac.authorization.k8s.io", Version: "v1alpha1", Resource: "roles"}

var rolesKind = pkgruntimeschema.GroupVersionKind{Group: "rbac.authorization.k8s.io", Version: "v1alpha1", Kind: "Role"}

// Get takes name of the role, and returns the corresponding role object, and an error if there is any.
func (c *FakeRoles) Get(ctx context.Context, name string, options apismetav1.GetOptions) (result *apirbacv1alpha1.Role, err error) {
	obj, err := c.Fake.
		Invokes(clientgotesting.NewGetAction(rolesResource, c.ns, name), &apirbacv1alpha1.Role{})

	if obj == nil {
		return nil, err
	}
	return obj.(*apirbacv1alpha1.Role), err
}

// List takes label and field selectors, and returns the list of Roles that match those selectors.
func (c *FakeRoles) List(ctx context.Context, opts apismetav1.ListOptions) (result *apirbacv1alpha1.RoleList, err error) {
	obj, err := c.Fake.
		Invokes(clientgotesting.NewListAction(rolesResource, rolesKind, c.ns, opts), &apirbacv1alpha1.RoleList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := clientgotesting.ExtractFromListOptions(opts)
	if label == nil {
		label = apimachinerypkglabels.Everything()
	}
	list := &apirbacv1alpha1.RoleList{ListMeta: obj.(*apirbacv1alpha1.RoleList).ListMeta}
	for _, item := range obj.(*apirbacv1alpha1.RoleList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a apimachinerypkgwatch.Interface that watches the requested roles.
func (c *FakeRoles) Watch(ctx context.Context, opts apismetav1.ListOptions) (apimachinerypkgwatch.Interface, error) {
	return c.Fake.
		InvokesWatch(clientgotesting.NewWatchAction(rolesResource, c.ns, opts))

}

// Create takes the representation of a role and creates it.  Returns the server's representation of the role, and an error, if there is any.
func (c *FakeRoles) Create(ctx context.Context, role *apirbacv1alpha1.Role, opts apismetav1.CreateOptions) (result *apirbacv1alpha1.Role, err error) {
	obj, err := c.Fake.
		Invokes(clientgotesting.NewCreateAction(rolesResource, c.ns, role), &apirbacv1alpha1.Role{})

	if obj == nil {
		return nil, err
	}
	return obj.(*apirbacv1alpha1.Role), err
}

// Update takes the representation of a role and updates it. Returns the server's representation of the role, and an error, if there is any.
func (c *FakeRoles) Update(ctx context.Context, role *apirbacv1alpha1.Role, opts apismetav1.UpdateOptions) (result *apirbacv1alpha1.Role, err error) {
	obj, err := c.Fake.
		Invokes(clientgotesting.NewUpdateAction(rolesResource, c.ns, role), &apirbacv1alpha1.Role{})

	if obj == nil {
		return nil, err
	}
	return obj.(*apirbacv1alpha1.Role), err
}

// Delete takes name of the role and deletes it. Returns an error if one occurs.
func (c *FakeRoles) Delete(ctx context.Context, name string, opts apismetav1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(clientgotesting.NewDeleteActionWithOptions(rolesResource, c.ns, name, opts), &apirbacv1alpha1.Role{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeRoles) DeleteCollection(ctx context.Context, opts apismetav1.DeleteOptions, listOpts apismetav1.ListOptions) error {
	action := clientgotesting.NewDeleteCollectionAction(rolesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &apirbacv1alpha1.RoleList{})
	return err
}

// Patch applies the patch and returns the patched role.
func (c *FakeRoles) Patch(ctx context.Context, name string, pt apimachinerypkgtypes.PatchType, data []byte, opts apismetav1.PatchOptions, subresources ...string) (result *apirbacv1alpha1.Role, err error) {
	obj, err := c.Fake.
		Invokes(clientgotesting.NewPatchSubresourceAction(rolesResource, c.ns, name, pt, data, subresources...), &apirbacv1alpha1.Role{})

	if obj == nil {
		return nil, err
	}
	return obj.(*apirbacv1alpha1.Role), err
}

// Apply takes the given apply declarative configuration, applies it and returns the applied role.
func (c *FakeRoles) Apply(ctx context.Context, role *applyconfigurationsrbacv1alpha1.RoleApplyConfiguration, opts apismetav1.ApplyOptions) (result *apirbacv1alpha1.Role, err error) {
	if role == nil {
		return nil, fmt.Errorf("role provided to Apply must not be nil")
	}
	data, err := json.Marshal(role)
	if err != nil {
		return nil, err
	}
	name := role.Name
	if name == nil {
		return nil, fmt.Errorf("role.Name must be provided to Apply")
	}
	obj, err := c.Fake.
		Invokes(clientgotesting.NewPatchSubresourceAction(rolesResource, c.ns, *name, apimachinerypkgtypes.ApplyPatchType, data), &apirbacv1alpha1.Role{})

	if obj == nil {
		return nil, err
	}
	return obj.(*apirbacv1alpha1.Role), err
}
