/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"
	"encoding/json"
	"fmt"

	apicorev1 "k8s.io/api/core/v1"
	apismetav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	apimachinerypkglabels "k8s.io/apimachinery/pkg/labels"
	pkgruntimeschema "k8s.io/apimachinery/pkg/runtime/schema"
	apimachinerypkgtypes "k8s.io/apimachinery/pkg/types"
	apimachinerypkgwatch "k8s.io/apimachinery/pkg/watch"
	applyconfigurationscorev1 "k8s.io/client-go/applyconfigurations/core/v1"
	clientgotesting "k8s.io/client-go/testing"
)

// FakeComponentStatuses implements ComponentStatusInterface
type FakeComponentStatuses struct {
	Fake *FakeCoreV1
}

var componentstatusesResource = pkgruntimeschema.GroupVersionResource{Group: "", Version: "v1", Resource: "componentstatuses"}

var componentstatusesKind = pkgruntimeschema.GroupVersionKind{Group: "", Version: "v1", Kind: "ComponentStatus"}

// Get takes name of the componentStatus, and returns the corresponding componentStatus object, and an error if there is any.
func (c *FakeComponentStatuses) Get(ctx context.Context, name string, options apismetav1.GetOptions) (result *apicorev1.ComponentStatus, err error) {
	obj, err := c.Fake.
		Invokes(clientgotesting.NewRootGetAction(componentstatusesResource, name), &apicorev1.ComponentStatus{})
	if obj == nil {
		return nil, err
	}
	return obj.(*apicorev1.ComponentStatus), err
}

// List takes label and field selectors, and returns the list of ComponentStatuses that match those selectors.
func (c *FakeComponentStatuses) List(ctx context.Context, opts apismetav1.ListOptions) (result *apicorev1.ComponentStatusList, err error) {
	obj, err := c.Fake.
		Invokes(clientgotesting.NewRootListAction(componentstatusesResource, componentstatusesKind, opts), &apicorev1.ComponentStatusList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := clientgotesting.ExtractFromListOptions(opts)
	if label == nil {
		label = apimachinerypkglabels.Everything()
	}
	list := &apicorev1.ComponentStatusList{ListMeta: obj.(*apicorev1.ComponentStatusList).ListMeta}
	for _, item := range obj.(*apicorev1.ComponentStatusList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a apimachinerypkgwatch.Interface that watches the requested componentStatuses.
func (c *FakeComponentStatuses) Watch(ctx context.Context, opts apismetav1.ListOptions) (apimachinerypkgwatch.Interface, error) {
	return c.Fake.
		InvokesWatch(clientgotesting.NewRootWatchAction(componentstatusesResource, opts))
}

// Create takes the representation of a componentStatus and creates it.  Returns the server's representation of the componentStatus, and an error, if there is any.
func (c *FakeComponentStatuses) Create(ctx context.Context, componentStatus *apicorev1.ComponentStatus, opts apismetav1.CreateOptions) (result *apicorev1.ComponentStatus, err error) {
	obj, err := c.Fake.
		Invokes(clientgotesting.NewRootCreateAction(componentstatusesResource, componentStatus), &apicorev1.ComponentStatus{})
	if obj == nil {
		return nil, err
	}
	return obj.(*apicorev1.ComponentStatus), err
}

// Update takes the representation of a componentStatus and updates it. Returns the server's representation of the componentStatus, and an error, if there is any.
func (c *FakeComponentStatuses) Update(ctx context.Context, componentStatus *apicorev1.ComponentStatus, opts apismetav1.UpdateOptions) (result *apicorev1.ComponentStatus, err error) {
	obj, err := c.Fake.
		Invokes(clientgotesting.NewRootUpdateAction(componentstatusesResource, componentStatus), &apicorev1.ComponentStatus{})
	if obj == nil {
		return nil, err
	}
	return obj.(*apicorev1.ComponentStatus), err
}

// Delete takes name of the componentStatus and deletes it. Returns an error if one occurs.
func (c *FakeComponentStatuses) Delete(ctx context.Context, name string, opts apismetav1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(clientgotesting.NewRootDeleteActionWithOptions(componentstatusesResource, name, opts), &apicorev1.ComponentStatus{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeComponentStatuses) DeleteCollection(ctx context.Context, opts apismetav1.DeleteOptions, listOpts apismetav1.ListOptions) error {
	action := clientgotesting.NewRootDeleteCollectionAction(componentstatusesResource, listOpts)

	_, err := c.Fake.Invokes(action, &apicorev1.ComponentStatusList{})
	return err
}

// Patch applies the patch and returns the patched componentStatus.
func (c *FakeComponentStatuses) Patch(ctx context.Context, name string, pt apimachinerypkgtypes.PatchType, data []byte, opts apismetav1.PatchOptions, subresources ...string) (result *apicorev1.ComponentStatus, err error) {
	obj, err := c.Fake.
		Invokes(clientgotesting.NewRootPatchSubresourceAction(componentstatusesResource, name, pt, data, subresources...), &apicorev1.ComponentStatus{})
	if obj == nil {
		return nil, err
	}
	return obj.(*apicorev1.ComponentStatus), err
}

// Apply takes the given apply declarative configuration, applies it and returns the applied componentStatus.
func (c *FakeComponentStatuses) Apply(ctx context.Context, componentStatus *applyconfigurationscorev1.ComponentStatusApplyConfiguration, opts apismetav1.ApplyOptions) (result *apicorev1.ComponentStatus, err error) {
	if componentStatus == nil {
		return nil, fmt.Errorf("componentStatus provided to Apply must not be nil")
	}
	data, err := json.Marshal(componentStatus)
	if err != nil {
		return nil, err
	}
	name := componentStatus.Name
	if name == nil {
		return nil, fmt.Errorf("componentStatus.Name must be provided to Apply")
	}
	obj, err := c.Fake.
		Invokes(clientgotesting.NewRootPatchSubresourceAction(componentstatusesResource, *name, apimachinerypkgtypes.ApplyPatchType, data), &apicorev1.ComponentStatus{})
	if obj == nil {
		return nil, err
	}
	return obj.(*apicorev1.ComponentStatus), err
}
