/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"
	"encoding/json"
	"fmt"

	apicorev1 "k8s.io/api/core/v1"
	apismetav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	apimachinerypkglabels "k8s.io/apimachinery/pkg/labels"
	pkgruntimeschema "k8s.io/apimachinery/pkg/runtime/schema"
	apimachinerypkgtypes "k8s.io/apimachinery/pkg/types"
	apimachinerypkgwatch "k8s.io/apimachinery/pkg/watch"
	applyconfigurationscorev1 "k8s.io/client-go/applyconfigurations/core/v1"
	clientgotesting "k8s.io/client-go/testing"
)

// FakeServices implements ServiceInterface
type FakeServices struct {
	Fake *FakeCoreV1
	ns   string
}

var servicesResource = pkgruntimeschema.GroupVersionResource{Group: "", Version: "v1", Resource: "services"}

var servicesKind = pkgruntimeschema.GroupVersionKind{Group: "", Version: "v1", Kind: "Service"}

// Get takes name of the service, and returns the corresponding service object, and an error if there is any.
func (c *FakeServices) Get(ctx context.Context, name string, options apismetav1.GetOptions) (result *apicorev1.Service, err error) {
	obj, err := c.Fake.
		Invokes(clientgotesting.NewGetAction(servicesResource, c.ns, name), &apicorev1.Service{})

	if obj == nil {
		return nil, err
	}
	return obj.(*apicorev1.Service), err
}

// List takes label and field selectors, and returns the list of Services that match those selectors.
func (c *FakeServices) List(ctx context.Context, opts apismetav1.ListOptions) (result *apicorev1.ServiceList, err error) {
	obj, err := c.Fake.
		Invokes(clientgotesting.NewListAction(servicesResource, servicesKind, c.ns, opts), &apicorev1.ServiceList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := clientgotesting.ExtractFromListOptions(opts)
	if label == nil {
		label = apimachinerypkglabels.Everything()
	}
	list := &apicorev1.ServiceList{ListMeta: obj.(*apicorev1.ServiceList).ListMeta}
	for _, item := range obj.(*apicorev1.ServiceList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a apimachinerypkgwatch.Interface that watches the requested services.
func (c *FakeServices) Watch(ctx context.Context, opts apismetav1.ListOptions) (apimachinerypkgwatch.Interface, error) {
	return c.Fake.
		InvokesWatch(clientgotesting.NewWatchAction(servicesResource, c.ns, opts))

}

// Create takes the representation of a service and creates it.  Returns the server's representation of the service, and an error, if there is any.
func (c *FakeServices) Create(ctx context.Context, service *apicorev1.Service, opts apismetav1.CreateOptions) (result *apicorev1.Service, err error) {
	obj, err := c.Fake.
		Invokes(clientgotesting.NewCreateAction(servicesResource, c.ns, service), &apicorev1.Service{})

	if obj == nil {
		return nil, err
	}
	return obj.(*apicorev1.Service), err
}

// Update takes the representation of a service and updates it. Returns the server's representation of the service, and an error, if there is any.
func (c *FakeServices) Update(ctx context.Context, service *apicorev1.Service, opts apismetav1.UpdateOptions) (result *apicorev1.Service, err error) {
	obj, err := c.Fake.
		Invokes(clientgotesting.NewUpdateAction(servicesResource, c.ns, service), &apicorev1.Service{})

	if obj == nil {
		return nil, err
	}
	return obj.(*apicorev1.Service), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeServices) UpdateStatus(ctx context.Context, service *apicorev1.Service, opts apismetav1.UpdateOptions) (*apicorev1.Service, error) {
	obj, err := c.Fake.
		Invokes(clientgotesting.NewUpdateSubresourceAction(servicesResource, "status", c.ns, service), &apicorev1.Service{})

	if obj == nil {
		return nil, err
	}
	return obj.(*apicorev1.Service), err
}

// Delete takes name of the service and deletes it. Returns an error if one occurs.
func (c *FakeServices) Delete(ctx context.Context, name string, opts apismetav1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(clientgotesting.NewDeleteActionWithOptions(servicesResource, c.ns, name, opts), &apicorev1.Service{})

	return err
}

// Patch applies the patch and returns the patched service.
func (c *FakeServices) Patch(ctx context.Context, name string, pt apimachinerypkgtypes.PatchType, data []byte, opts apismetav1.PatchOptions, subresources ...string) (result *apicorev1.Service, err error) {
	obj, err := c.Fake.
		Invokes(clientgotesting.NewPatchSubresourceAction(servicesResource, c.ns, name, pt, data, subresources...), &apicorev1.Service{})

	if obj == nil {
		return nil, err
	}
	return obj.(*apicorev1.Service), err
}

// Apply takes the given apply declarative configuration, applies it and returns the applied service.
func (c *FakeServices) Apply(ctx context.Context, service *applyconfigurationscorev1.ServiceApplyConfiguration, opts apismetav1.ApplyOptions) (result *apicorev1.Service, err error) {
	if service == nil {
		return nil, fmt.Errorf("service provided to Apply must not be nil")
	}
	data, err := json.Marshal(service)
	if err != nil {
		return nil, err
	}
	name := service.Name
	if name == nil {
		return nil, fmt.Errorf("service.Name must be provided to Apply")
	}
	obj, err := c.Fake.
		Invokes(clientgotesting.NewPatchSubresourceAction(servicesResource, c.ns, *name, apimachinerypkgtypes.ApplyPatchType, data), &apicorev1.Service{})

	if obj == nil {
		return nil, err
	}
	return obj.(*apicorev1.Service), err
}

// ApplyStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
func (c *FakeServices) ApplyStatus(ctx context.Context, service *applyconfigurationscorev1.ServiceApplyConfiguration, opts apismetav1.ApplyOptions) (result *apicorev1.Service, err error) {
	if service == nil {
		return nil, fmt.Errorf("service provided to Apply must not be nil")
	}
	data, err := json.Marshal(service)
	if err != nil {
		return nil, err
	}
	name := service.Name
	if name == nil {
		return nil, fmt.Errorf("service.Name must be provided to Apply")
	}
	obj, err := c.Fake.
		Invokes(clientgotesting.NewPatchSubresourceAction(servicesResource, c.ns, *name, apimachinerypkgtypes.ApplyPatchType, data, "status"), &apicorev1.Service{})

	if obj == nil {
		return nil, err
	}
	return obj.(*apicorev1.Service), err
}
