/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package apps

import (
	informersappsv1 "k8s.io/client-go/informers/apps/v1"
	informersappsv1beta1 "k8s.io/client-go/informers/apps/v1beta1"
	informersappsv1beta2 "k8s.io/client-go/informers/apps/v1beta2"
	clientgoinformersinternalinterfaces "k8s.io/client-go/informers/internalinterfaces"
)

// Interface provides access to each of this group's versions.
type Interface interface {
	// V1 provides access to shared informers for resources in V1.
	V1() informersappsv1.Interface
	// V1beta1 provides access to shared informers for resources in V1beta1.
	V1beta1() informersappsv1beta1.Interface
	// V1beta2 provides access to shared informers for resources in V1beta2.
	V1beta2() informersappsv1beta2.Interface
}

type group struct {
	factory          clientgoinformersinternalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions clientgoinformersinternalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f clientgoinformersinternalinterfaces.SharedInformerFactory, namespace string, tweakListOptions clientgoinformersinternalinterfaces.TweakListOptionsFunc) Interface {
	return &group{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// V1 returns a new informersappsv1.Interface.
func (g *group) V1() informersappsv1.Interface {
	return informersappsv1.New(g.factory, g.namespace, g.tweakListOptions)
}

// V1beta1 returns a new informersappsv1beta1.Interface.
func (g *group) V1beta1() informersappsv1beta1.Interface {
	return informersappsv1beta1.New(g.factory, g.namespace, g.tweakListOptions)
}

// V1beta2 returns a new informersappsv1beta2.Interface.
func (g *group) V1beta2() informersappsv1beta2.Interface {
	return informersappsv1beta2.New(g.factory, g.namespace, g.tweakListOptions)
}
