/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"
	"encoding/json"
	"fmt"

	apistoragev1beta1 "k8s.io/api/storage/v1beta1"
	apismetav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	apimachinerypkglabels "k8s.io/apimachinery/pkg/labels"
	pkgruntimeschema "k8s.io/apimachinery/pkg/runtime/schema"
	apimachinerypkgtypes "k8s.io/apimachinery/pkg/types"
	apimachinerypkgwatch "k8s.io/apimachinery/pkg/watch"
	applyconfigurationsstoragev1beta1 "k8s.io/client-go/applyconfigurations/storage/v1beta1"
	clientgotesting "k8s.io/client-go/testing"
)

// FakeCSIDrivers implements CSIDriverInterface
type FakeCSIDrivers struct {
	Fake *FakeStorageV1beta1
}

var csidriversResource = pkgruntimeschema.GroupVersionResource{Group: "storage.k8s.io", Version: "v1beta1", Resource: "csidrivers"}

var csidriversKind = pkgruntimeschema.GroupVersionKind{Group: "storage.k8s.io", Version: "v1beta1", Kind: "CSIDriver"}

// Get takes name of the cSIDriver, and returns the corresponding cSIDriver object, and an error if there is any.
func (c *FakeCSIDrivers) Get(ctx context.Context, name string, options apismetav1.GetOptions) (result *apistoragev1beta1.CSIDriver, err error) {
	obj, err := c.Fake.
		Invokes(clientgotesting.NewRootGetAction(csidriversResource, name), &apistoragev1beta1.CSIDriver{})
	if obj == nil {
		return nil, err
	}
	return obj.(*apistoragev1beta1.CSIDriver), err
}

// List takes label and field selectors, and returns the list of CSIDrivers that match those selectors.
func (c *FakeCSIDrivers) List(ctx context.Context, opts apismetav1.ListOptions) (result *apistoragev1beta1.CSIDriverList, err error) {
	obj, err := c.Fake.
		Invokes(clientgotesting.NewRootListAction(csidriversResource, csidriversKind, opts), &apistoragev1beta1.CSIDriverList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := clientgotesting.ExtractFromListOptions(opts)
	if label == nil {
		label = apimachinerypkglabels.Everything()
	}
	list := &apistoragev1beta1.CSIDriverList{ListMeta: obj.(*apistoragev1beta1.CSIDriverList).ListMeta}
	for _, item := range obj.(*apistoragev1beta1.CSIDriverList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a apimachinerypkgwatch.Interface that watches the requested cSIDrivers.
func (c *FakeCSIDrivers) Watch(ctx context.Context, opts apismetav1.ListOptions) (apimachinerypkgwatch.Interface, error) {
	return c.Fake.
		InvokesWatch(clientgotesting.NewRootWatchAction(csidriversResource, opts))
}

// Create takes the representation of a cSIDriver and creates it.  Returns the server's representation of the cSIDriver, and an error, if there is any.
func (c *FakeCSIDrivers) Create(ctx context.Context, cSIDriver *apistoragev1beta1.CSIDriver, opts apismetav1.CreateOptions) (result *apistoragev1beta1.CSIDriver, err error) {
	obj, err := c.Fake.
		Invokes(clientgotesting.NewRootCreateAction(csidriversResource, cSIDriver), &apistoragev1beta1.CSIDriver{})
	if obj == nil {
		return nil, err
	}
	return obj.(*apistoragev1beta1.CSIDriver), err
}

// Update takes the representation of a cSIDriver and updates it. Returns the server's representation of the cSIDriver, and an error, if there is any.
func (c *FakeCSIDrivers) Update(ctx context.Context, cSIDriver *apistoragev1beta1.CSIDriver, opts apismetav1.UpdateOptions) (result *apistoragev1beta1.CSIDriver, err error) {
	obj, err := c.Fake.
		Invokes(clientgotesting.NewRootUpdateAction(csidriversResource, cSIDriver), &apistoragev1beta1.CSIDriver{})
	if obj == nil {
		return nil, err
	}
	return obj.(*apistoragev1beta1.CSIDriver), err
}

// Delete takes name of the cSIDriver and deletes it. Returns an error if one occurs.
func (c *FakeCSIDrivers) Delete(ctx context.Context, name string, opts apismetav1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(clientgotesting.NewRootDeleteActionWithOptions(csidriversResource, name, opts), &apistoragev1beta1.CSIDriver{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeCSIDrivers) DeleteCollection(ctx context.Context, opts apismetav1.DeleteOptions, listOpts apismetav1.ListOptions) error {
	action := clientgotesting.NewRootDeleteCollectionAction(csidriversResource, listOpts)

	_, err := c.Fake.Invokes(action, &apistoragev1beta1.CSIDriverList{})
	return err
}

// Patch applies the patch and returns the patched cSIDriver.
func (c *FakeCSIDrivers) Patch(ctx context.Context, name string, pt apimachinerypkgtypes.PatchType, data []byte, opts apismetav1.PatchOptions, subresources ...string) (result *apistoragev1beta1.CSIDriver, err error) {
	obj, err := c.Fake.
		Invokes(clientgotesting.NewRootPatchSubresourceAction(csidriversResource, name, pt, data, subresources...), &apistoragev1beta1.CSIDriver{})
	if obj == nil {
		return nil, err
	}
	return obj.(*apistoragev1beta1.CSIDriver), err
}

// Apply takes the given apply declarative configuration, applies it and returns the applied cSIDriver.
func (c *FakeCSIDrivers) Apply(ctx context.Context, cSIDriver *applyconfigurationsstoragev1beta1.CSIDriverApplyConfiguration, opts apismetav1.ApplyOptions) (result *apistoragev1beta1.CSIDriver, err error) {
	if cSIDriver == nil {
		return nil, fmt.Errorf("cSIDriver provided to Apply must not be nil")
	}
	data, err := json.Marshal(cSIDriver)
	if err != nil {
		return nil, err
	}
	name := cSIDriver.Name
	if name == nil {
		return nil, fmt.Errorf("cSIDriver.Name must be provided to Apply")
	}
	obj, err := c.Fake.
		Invokes(clientgotesting.NewRootPatchSubresourceAction(csidriversResource, *name, apimachinerypkgtypes.ApplyPatchType, data), &apistoragev1beta1.CSIDriver{})
	if obj == nil {
		return nil, err
	}
	return obj.(*apistoragev1beta1.CSIDriver), err
}
