/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"
	"encoding/json"
	"fmt"

	apistoragev1beta1 "k8s.io/api/storage/v1beta1"
	apismetav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	apimachinerypkglabels "k8s.io/apimachinery/pkg/labels"
	pkgruntimeschema "k8s.io/apimachinery/pkg/runtime/schema"
	apimachinerypkgtypes "k8s.io/apimachinery/pkg/types"
	apimachinerypkgwatch "k8s.io/apimachinery/pkg/watch"
	applyconfigurationsstoragev1beta1 "k8s.io/client-go/applyconfigurations/storage/v1beta1"
	clientgotesting "k8s.io/client-go/testing"
)

// FakeCSINodes implements CSINodeInterface
type FakeCSINodes struct {
	Fake *FakeStorageV1beta1
}

var csinodesResource = pkgruntimeschema.GroupVersionResource{Group: "storage.k8s.io", Version: "v1beta1", Resource: "csinodes"}

var csinodesKind = pkgruntimeschema.GroupVersionKind{Group: "storage.k8s.io", Version: "v1beta1", Kind: "CSINode"}

// Get takes name of the cSINode, and returns the corresponding cSINode object, and an error if there is any.
func (c *FakeCSINodes) Get(ctx context.Context, name string, options apismetav1.GetOptions) (result *apistoragev1beta1.CSINode, err error) {
	obj, err := c.Fake.
		Invokes(clientgotesting.NewRootGetAction(csinodesResource, name), &apistoragev1beta1.CSINode{})
	if obj == nil {
		return nil, err
	}
	return obj.(*apistoragev1beta1.CSINode), err
}

// List takes label and field selectors, and returns the list of CSINodes that match those selectors.
func (c *FakeCSINodes) List(ctx context.Context, opts apismetav1.ListOptions) (result *apistoragev1beta1.CSINodeList, err error) {
	obj, err := c.Fake.
		Invokes(clientgotesting.NewRootListAction(csinodesResource, csinodesKind, opts), &apistoragev1beta1.CSINodeList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := clientgotesting.ExtractFromListOptions(opts)
	if label == nil {
		label = apimachinerypkglabels.Everything()
	}
	list := &apistoragev1beta1.CSINodeList{ListMeta: obj.(*apistoragev1beta1.CSINodeList).ListMeta}
	for _, item := range obj.(*apistoragev1beta1.CSINodeList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a apimachinerypkgwatch.Interface that watches the requested cSINodes.
func (c *FakeCSINodes) Watch(ctx context.Context, opts apismetav1.ListOptions) (apimachinerypkgwatch.Interface, error) {
	return c.Fake.
		InvokesWatch(clientgotesting.NewRootWatchAction(csinodesResource, opts))
}

// Create takes the representation of a cSINode and creates it.  Returns the server's representation of the cSINode, and an error, if there is any.
func (c *FakeCSINodes) Create(ctx context.Context, cSINode *apistoragev1beta1.CSINode, opts apismetav1.CreateOptions) (result *apistoragev1beta1.CSINode, err error) {
	obj, err := c.Fake.
		Invokes(clientgotesting.NewRootCreateAction(csinodesResource, cSINode), &apistoragev1beta1.CSINode{})
	if obj == nil {
		return nil, err
	}
	return obj.(*apistoragev1beta1.CSINode), err
}

// Update takes the representation of a cSINode and updates it. Returns the server's representation of the cSINode, and an error, if there is any.
func (c *FakeCSINodes) Update(ctx context.Context, cSINode *apistoragev1beta1.CSINode, opts apismetav1.UpdateOptions) (result *apistoragev1beta1.CSINode, err error) {
	obj, err := c.Fake.
		Invokes(clientgotesting.NewRootUpdateAction(csinodesResource, cSINode), &apistoragev1beta1.CSINode{})
	if obj == nil {
		return nil, err
	}
	return obj.(*apistoragev1beta1.CSINode), err
}

// Delete takes name of the cSINode and deletes it. Returns an error if one occurs.
func (c *FakeCSINodes) Delete(ctx context.Context, name string, opts apismetav1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(clientgotesting.NewRootDeleteActionWithOptions(csinodesResource, name, opts), &apistoragev1beta1.CSINode{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeCSINodes) DeleteCollection(ctx context.Context, opts apismetav1.DeleteOptions, listOpts apismetav1.ListOptions) error {
	action := clientgotesting.NewRootDeleteCollectionAction(csinodesResource, listOpts)

	_, err := c.Fake.Invokes(action, &apistoragev1beta1.CSINodeList{})
	return err
}

// Patch applies the patch and returns the patched cSINode.
func (c *FakeCSINodes) Patch(ctx context.Context, name string, pt apimachinerypkgtypes.PatchType, data []byte, opts apismetav1.PatchOptions, subresources ...string) (result *apistoragev1beta1.CSINode, err error) {
	obj, err := c.Fake.
		Invokes(clientgotesting.NewRootPatchSubresourceAction(csinodesResource, name, pt, data, subresources...), &apistoragev1beta1.CSINode{})
	if obj == nil {
		return nil, err
	}
	return obj.(*apistoragev1beta1.CSINode), err
}

// Apply takes the given apply declarative configuration, applies it and returns the applied cSINode.
func (c *FakeCSINodes) Apply(ctx context.Context, cSINode *applyconfigurationsstoragev1beta1.CSINodeApplyConfiguration, opts apismetav1.ApplyOptions) (result *apistoragev1beta1.CSINode, err error) {
	if cSINode == nil {
		return nil, fmt.Errorf("cSINode provided to Apply must not be nil")
	}
	data, err := json.Marshal(cSINode)
	if err != nil {
		return nil, err
	}
	name := cSINode.Name
	if name == nil {
		return nil, fmt.Errorf("cSINode.Name must be provided to Apply")
	}
	obj, err := c.Fake.
		Invokes(clientgotesting.NewRootPatchSubresourceAction(csinodesResource, *name, apimachinerypkgtypes.ApplyPatchType, data), &apistoragev1beta1.CSINode{})
	if obj == nil {
		return nil, err
	}
	return obj.(*apistoragev1beta1.CSINode), err
}
