/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	apiauthorizationv1beta1 "k8s.io/api/authorization/v1beta1"
	apismetav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	pkgruntimeschema "k8s.io/apimachinery/pkg/runtime/schema"
	clientgotesting "k8s.io/client-go/testing"
)

// FakeSelfSubjectAccessReviews implements SelfSubjectAccessReviewInterface
type FakeSelfSubjectAccessReviews struct {
	Fake *FakeAuthorizationV1beta1
}

var selfsubjectaccessreviewsResource = pkgruntimeschema.GroupVersionResource{Group: "authorization.k8s.io", Version: "v1beta1", Resource: "selfsubjectaccessreviews"}

var selfsubjectaccessreviewsKind = pkgruntimeschema.GroupVersionKind{Group: "authorization.k8s.io", Version: "v1beta1", Kind: "SelfSubjectAccessReview"}

// Create takes the representation of a selfSubjectAccessReview and creates it.  Returns the server's representation of the selfSubjectAccessReview, and an error, if there is any.
func (c *FakeSelfSubjectAccessReviews) Create(ctx context.Context, selfSubjectAccessReview *apiauthorizationv1beta1.SelfSubjectAccessReview, opts apismetav1.CreateOptions) (result *apiauthorizationv1beta1.SelfSubjectAccessReview, err error) {
	obj, err := c.Fake.
		Invokes(clientgotesting.NewRootCreateAction(selfsubjectaccessreviewsResource, selfSubjectAccessReview), &apiauthorizationv1beta1.SelfSubjectAccessReview{})
	if obj == nil {
		return nil, err
	}
	return obj.(*apiauthorizationv1beta1.SelfSubjectAccessReview), err
}
