// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "k8s.io/apiextensions-apiserver/examples/client-go/pkg/client/clientset/versioned/typed/cr/v1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeCrV1 struct {
	*testing.Fake
}

func (c *FakeCrV1) Examples(namespace string) v1.ExampleInterface {
	return &FakeExamples{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeCrV1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
