/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"
	"encoding/json"
	"fmt"

	apiappsv1 "k8s.io/api/apps/v1"
	apiautoscalingv1 "k8s.io/api/autoscaling/v1"
	apismetav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	apimachinerypkglabels "k8s.io/apimachinery/pkg/labels"
	pkgruntimeschema "k8s.io/apimachinery/pkg/runtime/schema"
	apimachinerypkgtypes "k8s.io/apimachinery/pkg/types"
	apimachinerypkgwatch "k8s.io/apimachinery/pkg/watch"
	applyconfigurationsappsv1 "k8s.io/client-go/applyconfigurations/apps/v1"
	applyconfigurationsautoscalingv1 "k8s.io/client-go/applyconfigurations/autoscaling/v1"
	clientgotesting "k8s.io/client-go/testing"
)

// FakeStatefulSets implements StatefulSetInterface
type FakeStatefulSets struct {
	Fake *FakeAppsV1
	ns   string
}

var statefulsetsResource = pkgruntimeschema.GroupVersionResource{Group: "apps", Version: "v1", Resource: "statefulsets"}

var statefulsetsKind = pkgruntimeschema.GroupVersionKind{Group: "apps", Version: "v1", Kind: "StatefulSet"}

// Get takes name of the statefulSet, and returns the corresponding statefulSet object, and an error if there is any.
func (c *FakeStatefulSets) Get(ctx context.Context, name string, options apismetav1.GetOptions) (result *apiappsv1.StatefulSet, err error) {
	obj, err := c.Fake.
		Invokes(clientgotesting.NewGetAction(statefulsetsResource, c.ns, name), &apiappsv1.StatefulSet{})

	if obj == nil {
		return nil, err
	}
	return obj.(*apiappsv1.StatefulSet), err
}

// List takes label and field selectors, and returns the list of StatefulSets that match those selectors.
func (c *FakeStatefulSets) List(ctx context.Context, opts apismetav1.ListOptions) (result *apiappsv1.StatefulSetList, err error) {
	obj, err := c.Fake.
		Invokes(clientgotesting.NewListAction(statefulsetsResource, statefulsetsKind, c.ns, opts), &apiappsv1.StatefulSetList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := clientgotesting.ExtractFromListOptions(opts)
	if label == nil {
		label = apimachinerypkglabels.Everything()
	}
	list := &apiappsv1.StatefulSetList{ListMeta: obj.(*apiappsv1.StatefulSetList).ListMeta}
	for _, item := range obj.(*apiappsv1.StatefulSetList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a apimachinerypkgwatch.Interface that watches the requested statefulSets.
func (c *FakeStatefulSets) Watch(ctx context.Context, opts apismetav1.ListOptions) (apimachinerypkgwatch.Interface, error) {
	return c.Fake.
		InvokesWatch(clientgotesting.NewWatchAction(statefulsetsResource, c.ns, opts))

}

// Create takes the representation of a statefulSet and creates it.  Returns the server's representation of the statefulSet, and an error, if there is any.
func (c *FakeStatefulSets) Create(ctx context.Context, statefulSet *apiappsv1.StatefulSet, opts apismetav1.CreateOptions) (result *apiappsv1.StatefulSet, err error) {
	obj, err := c.Fake.
		Invokes(clientgotesting.NewCreateAction(statefulsetsResource, c.ns, statefulSet), &apiappsv1.StatefulSet{})

	if obj == nil {
		return nil, err
	}
	return obj.(*apiappsv1.StatefulSet), err
}

// Update takes the representation of a statefulSet and updates it. Returns the server's representation of the statefulSet, and an error, if there is any.
func (c *FakeStatefulSets) Update(ctx context.Context, statefulSet *apiappsv1.StatefulSet, opts apismetav1.UpdateOptions) (result *apiappsv1.StatefulSet, err error) {
	obj, err := c.Fake.
		Invokes(clientgotesting.NewUpdateAction(statefulsetsResource, c.ns, statefulSet), &apiappsv1.StatefulSet{})

	if obj == nil {
		return nil, err
	}
	return obj.(*apiappsv1.StatefulSet), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeStatefulSets) UpdateStatus(ctx context.Context, statefulSet *apiappsv1.StatefulSet, opts apismetav1.UpdateOptions) (*apiappsv1.StatefulSet, error) {
	obj, err := c.Fake.
		Invokes(clientgotesting.NewUpdateSubresourceAction(statefulsetsResource, "status", c.ns, statefulSet), &apiappsv1.StatefulSet{})

	if obj == nil {
		return nil, err
	}
	return obj.(*apiappsv1.StatefulSet), err
}

// Delete takes name of the statefulSet and deletes it. Returns an error if one occurs.
func (c *FakeStatefulSets) Delete(ctx context.Context, name string, opts apismetav1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(clientgotesting.NewDeleteActionWithOptions(statefulsetsResource, c.ns, name, opts), &apiappsv1.StatefulSet{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeStatefulSets) DeleteCollection(ctx context.Context, opts apismetav1.DeleteOptions, listOpts apismetav1.ListOptions) error {
	action := clientgotesting.NewDeleteCollectionAction(statefulsetsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &apiappsv1.StatefulSetList{})
	return err
}

// Patch applies the patch and returns the patched statefulSet.
func (c *FakeStatefulSets) Patch(ctx context.Context, name string, pt apimachinerypkgtypes.PatchType, data []byte, opts apismetav1.PatchOptions, subresources ...string) (result *apiappsv1.StatefulSet, err error) {
	obj, err := c.Fake.
		Invokes(clientgotesting.NewPatchSubresourceAction(statefulsetsResource, c.ns, name, pt, data, subresources...), &apiappsv1.StatefulSet{})

	if obj == nil {
		return nil, err
	}
	return obj.(*apiappsv1.StatefulSet), err
}

// Apply takes the given apply declarative configuration, applies it and returns the applied statefulSet.
func (c *FakeStatefulSets) Apply(ctx context.Context, statefulSet *applyconfigurationsappsv1.StatefulSetApplyConfiguration, opts apismetav1.ApplyOptions) (result *apiappsv1.StatefulSet, err error) {
	if statefulSet == nil {
		return nil, fmt.Errorf("statefulSet provided to Apply must not be nil")
	}
	data, err := json.Marshal(statefulSet)
	if err != nil {
		return nil, err
	}
	name := statefulSet.Name
	if name == nil {
		return nil, fmt.Errorf("statefulSet.Name must be provided to Apply")
	}
	obj, err := c.Fake.
		Invokes(clientgotesting.NewPatchSubresourceAction(statefulsetsResource, c.ns, *name, apimachinerypkgtypes.ApplyPatchType, data), &apiappsv1.StatefulSet{})

	if obj == nil {
		return nil, err
	}
	return obj.(*apiappsv1.StatefulSet), err
}

// ApplyStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
func (c *FakeStatefulSets) ApplyStatus(ctx context.Context, statefulSet *applyconfigurationsappsv1.StatefulSetApplyConfiguration, opts apismetav1.ApplyOptions) (result *apiappsv1.StatefulSet, err error) {
	if statefulSet == nil {
		return nil, fmt.Errorf("statefulSet provided to Apply must not be nil")
	}
	data, err := json.Marshal(statefulSet)
	if err != nil {
		return nil, err
	}
	name := statefulSet.Name
	if name == nil {
		return nil, fmt.Errorf("statefulSet.Name must be provided to Apply")
	}
	obj, err := c.Fake.
		Invokes(clientgotesting.NewPatchSubresourceAction(statefulsetsResource, c.ns, *name, apimachinerypkgtypes.ApplyPatchType, data, "status"), &apiappsv1.StatefulSet{})

	if obj == nil {
		return nil, err
	}
	return obj.(*apiappsv1.StatefulSet), err
}

// GetScale takes name of the statefulSet, and returns the corresponding scale object, and an error if there is any.
func (c *FakeStatefulSets) GetScale(ctx context.Context, statefulSetName string, options apismetav1.GetOptions) (result *apiautoscalingv1.Scale, err error) {
	obj, err := c.Fake.
		Invokes(clientgotesting.NewGetSubresourceAction(statefulsetsResource, c.ns, "scale", statefulSetName), &apiautoscalingv1.Scale{})

	if obj == nil {
		return nil, err
	}
	return obj.(*apiautoscalingv1.Scale), err
}

// UpdateScale takes the representation of a scale and updates it. Returns the server's representation of the scale, and an error, if there is any.
func (c *FakeStatefulSets) UpdateScale(ctx context.Context, statefulSetName string, scale *apiautoscalingv1.Scale, opts apismetav1.UpdateOptions) (result *apiautoscalingv1.Scale, err error) {
	obj, err := c.Fake.
		Invokes(clientgotesting.NewUpdateSubresourceAction(statefulsetsResource, "scale", c.ns, scale), &apiautoscalingv1.Scale{})

	if obj == nil {
		return nil, err
	}
	return obj.(*apiautoscalingv1.Scale), err
}

// ApplyScale takes top resource name and the apply declarative configuration for scale,
// applies it and returns the applied scale, and an error, if there is any.
func (c *FakeStatefulSets) ApplyScale(ctx context.Context, statefulSetName string, scale *applyconfigurationsautoscalingv1.ScaleApplyConfiguration, opts apismetav1.ApplyOptions) (result *apiautoscalingv1.Scale, err error) {
	if scale == nil {
		return nil, fmt.Errorf("scale provided to ApplyScale must not be nil")
	}
	data, err := json.Marshal(scale)
	if err != nil {
		return nil, err
	}
	obj, err := c.Fake.
		Invokes(clientgotesting.NewPatchSubresourceAction(statefulsetsResource, c.ns, statefulSetName, apimachinerypkgtypes.ApplyPatchType, data, "status"), &apiautoscalingv1.Scale{})

	if obj == nil {
		return nil, err
	}
	return obj.(*apiautoscalingv1.Scale), err
}
