/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"
	"encoding/json"
	"fmt"

	apischedulingv1beta1 "k8s.io/api/scheduling/v1beta1"
	apismetav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	apimachinerypkglabels "k8s.io/apimachinery/pkg/labels"
	pkgruntimeschema "k8s.io/apimachinery/pkg/runtime/schema"
	apimachinerypkgtypes "k8s.io/apimachinery/pkg/types"
	apimachinerypkgwatch "k8s.io/apimachinery/pkg/watch"
	applyconfigurationsschedulingv1beta1 "k8s.io/client-go/applyconfigurations/scheduling/v1beta1"
	clientgotesting "k8s.io/client-go/testing"
)

// FakePriorityClasses implements PriorityClassInterface
type FakePriorityClasses struct {
	Fake *FakeSchedulingV1beta1
}

var priorityclassesResource = pkgruntimeschema.GroupVersionResource{Group: "scheduling.k8s.io", Version: "v1beta1", Resource: "priorityclasses"}

var priorityclassesKind = pkgruntimeschema.GroupVersionKind{Group: "scheduling.k8s.io", Version: "v1beta1", Kind: "PriorityClass"}

// Get takes name of the priorityClass, and returns the corresponding priorityClass object, and an error if there is any.
func (c *FakePriorityClasses) Get(ctx context.Context, name string, options apismetav1.GetOptions) (result *apischedulingv1beta1.PriorityClass, err error) {
	obj, err := c.Fake.
		Invokes(clientgotesting.NewRootGetAction(priorityclassesResource, name), &apischedulingv1beta1.PriorityClass{})
	if obj == nil {
		return nil, err
	}
	return obj.(*apischedulingv1beta1.PriorityClass), err
}

// List takes label and field selectors, and returns the list of PriorityClasses that match those selectors.
func (c *FakePriorityClasses) List(ctx context.Context, opts apismetav1.ListOptions) (result *apischedulingv1beta1.PriorityClassList, err error) {
	obj, err := c.Fake.
		Invokes(clientgotesting.NewRootListAction(priorityclassesResource, priorityclassesKind, opts), &apischedulingv1beta1.PriorityClassList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := clientgotesting.ExtractFromListOptions(opts)
	if label == nil {
		label = apimachinerypkglabels.Everything()
	}
	list := &apischedulingv1beta1.PriorityClassList{ListMeta: obj.(*apischedulingv1beta1.PriorityClassList).ListMeta}
	for _, item := range obj.(*apischedulingv1beta1.PriorityClassList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a apimachinerypkgwatch.Interface that watches the requested priorityClasses.
func (c *FakePriorityClasses) Watch(ctx context.Context, opts apismetav1.ListOptions) (apimachinerypkgwatch.Interface, error) {
	return c.Fake.
		InvokesWatch(clientgotesting.NewRootWatchAction(priorityclassesResource, opts))
}

// Create takes the representation of a priorityClass and creates it.  Returns the server's representation of the priorityClass, and an error, if there is any.
func (c *FakePriorityClasses) Create(ctx context.Context, priorityClass *apischedulingv1beta1.PriorityClass, opts apismetav1.CreateOptions) (result *apischedulingv1beta1.PriorityClass, err error) {
	obj, err := c.Fake.
		Invokes(clientgotesting.NewRootCreateAction(priorityclassesResource, priorityClass), &apischedulingv1beta1.PriorityClass{})
	if obj == nil {
		return nil, err
	}
	return obj.(*apischedulingv1beta1.PriorityClass), err
}

// Update takes the representation of a priorityClass and updates it. Returns the server's representation of the priorityClass, and an error, if there is any.
func (c *FakePriorityClasses) Update(ctx context.Context, priorityClass *apischedulingv1beta1.PriorityClass, opts apismetav1.UpdateOptions) (result *apischedulingv1beta1.PriorityClass, err error) {
	obj, err := c.Fake.
		Invokes(clientgotesting.NewRootUpdateAction(priorityclassesResource, priorityClass), &apischedulingv1beta1.PriorityClass{})
	if obj == nil {
		return nil, err
	}
	return obj.(*apischedulingv1beta1.PriorityClass), err
}

// Delete takes name of the priorityClass and deletes it. Returns an error if one occurs.
func (c *FakePriorityClasses) Delete(ctx context.Context, name string, opts apismetav1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(clientgotesting.NewRootDeleteActionWithOptions(priorityclassesResource, name, opts), &apischedulingv1beta1.PriorityClass{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakePriorityClasses) DeleteCollection(ctx context.Context, opts apismetav1.DeleteOptions, listOpts apismetav1.ListOptions) error {
	action := clientgotesting.NewRootDeleteCollectionAction(priorityclassesResource, listOpts)

	_, err := c.Fake.Invokes(action, &apischedulingv1beta1.PriorityClassList{})
	return err
}

// Patch applies the patch and returns the patched priorityClass.
func (c *FakePriorityClasses) Patch(ctx context.Context, name string, pt apimachinerypkgtypes.PatchType, data []byte, opts apismetav1.PatchOptions, subresources ...string) (result *apischedulingv1beta1.PriorityClass, err error) {
	obj, err := c.Fake.
		Invokes(clientgotesting.NewRootPatchSubresourceAction(priorityclassesResource, name, pt, data, subresources...), &apischedulingv1beta1.PriorityClass{})
	if obj == nil {
		return nil, err
	}
	return obj.(*apischedulingv1beta1.PriorityClass), err
}

// Apply takes the given apply declarative configuration, applies it and returns the applied priorityClass.
func (c *FakePriorityClasses) Apply(ctx context.Context, priorityClass *applyconfigurationsschedulingv1beta1.PriorityClassApplyConfiguration, opts apismetav1.ApplyOptions) (result *apischedulingv1beta1.PriorityClass, err error) {
	if priorityClass == nil {
		return nil, fmt.Errorf("priorityClass provided to Apply must not be nil")
	}
	data, err := json.Marshal(priorityClass)
	if err != nil {
		return nil, err
	}
	name := priorityClass.Name
	if name == nil {
		return nil, fmt.Errorf("priorityClass.Name must be provided to Apply")
	}
	obj, err := c.Fake.
		Invokes(clientgotesting.NewRootPatchSubresourceAction(priorityclassesResource, *name, apimachinerypkgtypes.ApplyPatchType, data), &apischedulingv1beta1.PriorityClass{})
	if obj == nil {
		return nil, err
	}
	return obj.(*apischedulingv1beta1.PriorityClass), err
}
