/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"
	"encoding/json"
	"fmt"

	apiextensionsv1beta1 "k8s.io/api/extensions/v1beta1"
	apismetav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	apimachinerypkglabels "k8s.io/apimachinery/pkg/labels"
	pkgruntimeschema "k8s.io/apimachinery/pkg/runtime/schema"
	apimachinerypkgtypes "k8s.io/apimachinery/pkg/types"
	apimachinerypkgwatch "k8s.io/apimachinery/pkg/watch"
	applyconfigurationsextensionsv1beta1 "k8s.io/client-go/applyconfigurations/extensions/v1beta1"
	clientgotesting "k8s.io/client-go/testing"
)

// FakeDeployments implements DeploymentInterface
type FakeDeployments struct {
	Fake *FakeExtensionsV1beta1
	ns   string
}

var deploymentsResource = pkgruntimeschema.GroupVersionResource{Group: "extensions", Version: "v1beta1", Resource: "deployments"}

var deploymentsKind = pkgruntimeschema.GroupVersionKind{Group: "extensions", Version: "v1beta1", Kind: "Deployment"}

// Get takes name of the deployment, and returns the corresponding deployment object, and an error if there is any.
func (c *FakeDeployments) Get(ctx context.Context, name string, options apismetav1.GetOptions) (result *apiextensionsv1beta1.Deployment, err error) {
	obj, err := c.Fake.
		Invokes(clientgotesting.NewGetAction(deploymentsResource, c.ns, name), &apiextensionsv1beta1.Deployment{})

	if obj == nil {
		return nil, err
	}
	return obj.(*apiextensionsv1beta1.Deployment), err
}

// List takes label and field selectors, and returns the list of Deployments that match those selectors.
func (c *FakeDeployments) List(ctx context.Context, opts apismetav1.ListOptions) (result *apiextensionsv1beta1.DeploymentList, err error) {
	obj, err := c.Fake.
		Invokes(clientgotesting.NewListAction(deploymentsResource, deploymentsKind, c.ns, opts), &apiextensionsv1beta1.DeploymentList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := clientgotesting.ExtractFromListOptions(opts)
	if label == nil {
		label = apimachinerypkglabels.Everything()
	}
	list := &apiextensionsv1beta1.DeploymentList{ListMeta: obj.(*apiextensionsv1beta1.DeploymentList).ListMeta}
	for _, item := range obj.(*apiextensionsv1beta1.DeploymentList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a apimachinerypkgwatch.Interface that watches the requested deployments.
func (c *FakeDeployments) Watch(ctx context.Context, opts apismetav1.ListOptions) (apimachinerypkgwatch.Interface, error) {
	return c.Fake.
		InvokesWatch(clientgotesting.NewWatchAction(deploymentsResource, c.ns, opts))

}

// Create takes the representation of a deployment and creates it.  Returns the server's representation of the deployment, and an error, if there is any.
func (c *FakeDeployments) Create(ctx context.Context, deployment *apiextensionsv1beta1.Deployment, opts apismetav1.CreateOptions) (result *apiextensionsv1beta1.Deployment, err error) {
	obj, err := c.Fake.
		Invokes(clientgotesting.NewCreateAction(deploymentsResource, c.ns, deployment), &apiextensionsv1beta1.Deployment{})

	if obj == nil {
		return nil, err
	}
	return obj.(*apiextensionsv1beta1.Deployment), err
}

// Update takes the representation of a deployment and updates it. Returns the server's representation of the deployment, and an error, if there is any.
func (c *FakeDeployments) Update(ctx context.Context, deployment *apiextensionsv1beta1.Deployment, opts apismetav1.UpdateOptions) (result *apiextensionsv1beta1.Deployment, err error) {
	obj, err := c.Fake.
		Invokes(clientgotesting.NewUpdateAction(deploymentsResource, c.ns, deployment), &apiextensionsv1beta1.Deployment{})

	if obj == nil {
		return nil, err
	}
	return obj.(*apiextensionsv1beta1.Deployment), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeDeployments) UpdateStatus(ctx context.Context, deployment *apiextensionsv1beta1.Deployment, opts apismetav1.UpdateOptions) (*apiextensionsv1beta1.Deployment, error) {
	obj, err := c.Fake.
		Invokes(clientgotesting.NewUpdateSubresourceAction(deploymentsResource, "status", c.ns, deployment), &apiextensionsv1beta1.Deployment{})

	if obj == nil {
		return nil, err
	}
	return obj.(*apiextensionsv1beta1.Deployment), err
}

// Delete takes name of the deployment and deletes it. Returns an error if one occurs.
func (c *FakeDeployments) Delete(ctx context.Context, name string, opts apismetav1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(clientgotesting.NewDeleteActionWithOptions(deploymentsResource, c.ns, name, opts), &apiextensionsv1beta1.Deployment{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeDeployments) DeleteCollection(ctx context.Context, opts apismetav1.DeleteOptions, listOpts apismetav1.ListOptions) error {
	action := clientgotesting.NewDeleteCollectionAction(deploymentsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &apiextensionsv1beta1.DeploymentList{})
	return err
}

// Patch applies the patch and returns the patched deployment.
func (c *FakeDeployments) Patch(ctx context.Context, name string, pt apimachinerypkgtypes.PatchType, data []byte, opts apismetav1.PatchOptions, subresources ...string) (result *apiextensionsv1beta1.Deployment, err error) {
	obj, err := c.Fake.
		Invokes(clientgotesting.NewPatchSubresourceAction(deploymentsResource, c.ns, name, pt, data, subresources...), &apiextensionsv1beta1.Deployment{})

	if obj == nil {
		return nil, err
	}
	return obj.(*apiextensionsv1beta1.Deployment), err
}

// Apply takes the given apply declarative configuration, applies it and returns the applied deployment.
func (c *FakeDeployments) Apply(ctx context.Context, deployment *applyconfigurationsextensionsv1beta1.DeploymentApplyConfiguration, opts apismetav1.ApplyOptions) (result *apiextensionsv1beta1.Deployment, err error) {
	if deployment == nil {
		return nil, fmt.Errorf("deployment provided to Apply must not be nil")
	}
	data, err := json.Marshal(deployment)
	if err != nil {
		return nil, err
	}
	name := deployment.Name
	if name == nil {
		return nil, fmt.Errorf("deployment.Name must be provided to Apply")
	}
	obj, err := c.Fake.
		Invokes(clientgotesting.NewPatchSubresourceAction(deploymentsResource, c.ns, *name, apimachinerypkgtypes.ApplyPatchType, data), &apiextensionsv1beta1.Deployment{})

	if obj == nil {
		return nil, err
	}
	return obj.(*apiextensionsv1beta1.Deployment), err
}

// ApplyStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
func (c *FakeDeployments) ApplyStatus(ctx context.Context, deployment *applyconfigurationsextensionsv1beta1.DeploymentApplyConfiguration, opts apismetav1.ApplyOptions) (result *apiextensionsv1beta1.Deployment, err error) {
	if deployment == nil {
		return nil, fmt.Errorf("deployment provided to Apply must not be nil")
	}
	data, err := json.Marshal(deployment)
	if err != nil {
		return nil, err
	}
	name := deployment.Name
	if name == nil {
		return nil, fmt.Errorf("deployment.Name must be provided to Apply")
	}
	obj, err := c.Fake.
		Invokes(clientgotesting.NewPatchSubresourceAction(deploymentsResource, c.ns, *name, apimachinerypkgtypes.ApplyPatchType, data, "status"), &apiextensionsv1beta1.Deployment{})

	if obj == nil {
		return nil, err
	}
	return obj.(*apiextensionsv1beta1.Deployment), err
}

// GetScale takes name of the deployment, and returns the corresponding scale object, and an error if there is any.
func (c *FakeDeployments) GetScale(ctx context.Context, deploymentName string, options apismetav1.GetOptions) (result *apiextensionsv1beta1.Scale, err error) {
	obj, err := c.Fake.
		Invokes(clientgotesting.NewGetSubresourceAction(deploymentsResource, c.ns, "scale", deploymentName), &apiextensionsv1beta1.Scale{})

	if obj == nil {
		return nil, err
	}
	return obj.(*apiextensionsv1beta1.Scale), err
}

// UpdateScale takes the representation of a scale and updates it. Returns the server's representation of the scale, and an error, if there is any.
func (c *FakeDeployments) UpdateScale(ctx context.Context, deploymentName string, scale *apiextensionsv1beta1.Scale, opts apismetav1.UpdateOptions) (result *apiextensionsv1beta1.Scale, err error) {
	obj, err := c.Fake.
		Invokes(clientgotesting.NewUpdateSubresourceAction(deploymentsResource, "scale", c.ns, scale), &apiextensionsv1beta1.Scale{})

	if obj == nil {
		return nil, err
	}
	return obj.(*apiextensionsv1beta1.Scale), err
}

// ApplyScale takes top resource name and the apply declarative configuration for scale,
// applies it and returns the applied scale, and an error, if there is any.
func (c *FakeDeployments) ApplyScale(ctx context.Context, deploymentName string, scale *applyconfigurationsextensionsv1beta1.ScaleApplyConfiguration, opts apismetav1.ApplyOptions) (result *apiextensionsv1beta1.Scale, err error) {
	if scale == nil {
		return nil, fmt.Errorf("scale provided to ApplyScale must not be nil")
	}
	data, err := json.Marshal(scale)
	if err != nil {
		return nil, err
	}
	obj, err := c.Fake.
		Invokes(clientgotesting.NewPatchSubresourceAction(deploymentsResource, c.ns, deploymentName, apimachinerypkgtypes.ApplyPatchType, data, "status"), &apiextensionsv1beta1.Scale{})

	if obj == nil {
		return nil, err
	}
	return obj.(*apiextensionsv1beta1.Scale), err
}
