/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"
	"encoding/json"
	"fmt"

	apiextensionsv1beta1 "k8s.io/api/extensions/v1beta1"
	apismetav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	apimachinerypkglabels "k8s.io/apimachinery/pkg/labels"
	pkgruntimeschema "k8s.io/apimachinery/pkg/runtime/schema"
	apimachinerypkgtypes "k8s.io/apimachinery/pkg/types"
	apimachinerypkgwatch "k8s.io/apimachinery/pkg/watch"
	applyconfigurationsextensionsv1beta1 "k8s.io/client-go/applyconfigurations/extensions/v1beta1"
	clientgotesting "k8s.io/client-go/testing"
)

// FakeNetworkPolicies implements NetworkPolicyInterface
type FakeNetworkPolicies struct {
	Fake *FakeExtensionsV1beta1
	ns   string
}

var networkpoliciesResource = pkgruntimeschema.GroupVersionResource{Group: "extensions", Version: "v1beta1", Resource: "networkpolicies"}

var networkpoliciesKind = pkgruntimeschema.GroupVersionKind{Group: "extensions", Version: "v1beta1", Kind: "NetworkPolicy"}

// Get takes name of the networkPolicy, and returns the corresponding networkPolicy object, and an error if there is any.
func (c *FakeNetworkPolicies) Get(ctx context.Context, name string, options apismetav1.GetOptions) (result *apiextensionsv1beta1.NetworkPolicy, err error) {
	obj, err := c.Fake.
		Invokes(clientgotesting.NewGetAction(networkpoliciesResource, c.ns, name), &apiextensionsv1beta1.NetworkPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*apiextensionsv1beta1.NetworkPolicy), err
}

// List takes label and field selectors, and returns the list of NetworkPolicies that match those selectors.
func (c *FakeNetworkPolicies) List(ctx context.Context, opts apismetav1.ListOptions) (result *apiextensionsv1beta1.NetworkPolicyList, err error) {
	obj, err := c.Fake.
		Invokes(clientgotesting.NewListAction(networkpoliciesResource, networkpoliciesKind, c.ns, opts), &apiextensionsv1beta1.NetworkPolicyList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := clientgotesting.ExtractFromListOptions(opts)
	if label == nil {
		label = apimachinerypkglabels.Everything()
	}
	list := &apiextensionsv1beta1.NetworkPolicyList{ListMeta: obj.(*apiextensionsv1beta1.NetworkPolicyList).ListMeta}
	for _, item := range obj.(*apiextensionsv1beta1.NetworkPolicyList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a apimachinerypkgwatch.Interface that watches the requested networkPolicies.
func (c *FakeNetworkPolicies) Watch(ctx context.Context, opts apismetav1.ListOptions) (apimachinerypkgwatch.Interface, error) {
	return c.Fake.
		InvokesWatch(clientgotesting.NewWatchAction(networkpoliciesResource, c.ns, opts))

}

// Create takes the representation of a networkPolicy and creates it.  Returns the server's representation of the networkPolicy, and an error, if there is any.
func (c *FakeNetworkPolicies) Create(ctx context.Context, networkPolicy *apiextensionsv1beta1.NetworkPolicy, opts apismetav1.CreateOptions) (result *apiextensionsv1beta1.NetworkPolicy, err error) {
	obj, err := c.Fake.
		Invokes(clientgotesting.NewCreateAction(networkpoliciesResource, c.ns, networkPolicy), &apiextensionsv1beta1.NetworkPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*apiextensionsv1beta1.NetworkPolicy), err
}

// Update takes the representation of a networkPolicy and updates it. Returns the server's representation of the networkPolicy, and an error, if there is any.
func (c *FakeNetworkPolicies) Update(ctx context.Context, networkPolicy *apiextensionsv1beta1.NetworkPolicy, opts apismetav1.UpdateOptions) (result *apiextensionsv1beta1.NetworkPolicy, err error) {
	obj, err := c.Fake.
		Invokes(clientgotesting.NewUpdateAction(networkpoliciesResource, c.ns, networkPolicy), &apiextensionsv1beta1.NetworkPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*apiextensionsv1beta1.NetworkPolicy), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeNetworkPolicies) UpdateStatus(ctx context.Context, networkPolicy *apiextensionsv1beta1.NetworkPolicy, opts apismetav1.UpdateOptions) (*apiextensionsv1beta1.NetworkPolicy, error) {
	obj, err := c.Fake.
		Invokes(clientgotesting.NewUpdateSubresourceAction(networkpoliciesResource, "status", c.ns, networkPolicy), &apiextensionsv1beta1.NetworkPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*apiextensionsv1beta1.NetworkPolicy), err
}

// Delete takes name of the networkPolicy and deletes it. Returns an error if one occurs.
func (c *FakeNetworkPolicies) Delete(ctx context.Context, name string, opts apismetav1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(clientgotesting.NewDeleteActionWithOptions(networkpoliciesResource, c.ns, name, opts), &apiextensionsv1beta1.NetworkPolicy{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeNetworkPolicies) DeleteCollection(ctx context.Context, opts apismetav1.DeleteOptions, listOpts apismetav1.ListOptions) error {
	action := clientgotesting.NewDeleteCollectionAction(networkpoliciesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &apiextensionsv1beta1.NetworkPolicyList{})
	return err
}

// Patch applies the patch and returns the patched networkPolicy.
func (c *FakeNetworkPolicies) Patch(ctx context.Context, name string, pt apimachinerypkgtypes.PatchType, data []byte, opts apismetav1.PatchOptions, subresources ...string) (result *apiextensionsv1beta1.NetworkPolicy, err error) {
	obj, err := c.Fake.
		Invokes(clientgotesting.NewPatchSubresourceAction(networkpoliciesResource, c.ns, name, pt, data, subresources...), &apiextensionsv1beta1.NetworkPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*apiextensionsv1beta1.NetworkPolicy), err
}

// Apply takes the given apply declarative configuration, applies it and returns the applied networkPolicy.
func (c *FakeNetworkPolicies) Apply(ctx context.Context, networkPolicy *applyconfigurationsextensionsv1beta1.NetworkPolicyApplyConfiguration, opts apismetav1.ApplyOptions) (result *apiextensionsv1beta1.NetworkPolicy, err error) {
	if networkPolicy == nil {
		return nil, fmt.Errorf("networkPolicy provided to Apply must not be nil")
	}
	data, err := json.Marshal(networkPolicy)
	if err != nil {
		return nil, err
	}
	name := networkPolicy.Name
	if name == nil {
		return nil, fmt.Errorf("networkPolicy.Name must be provided to Apply")
	}
	obj, err := c.Fake.
		Invokes(clientgotesting.NewPatchSubresourceAction(networkpoliciesResource, c.ns, *name, apimachinerypkgtypes.ApplyPatchType, data), &apiextensionsv1beta1.NetworkPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*apiextensionsv1beta1.NetworkPolicy), err
}

// ApplyStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
func (c *FakeNetworkPolicies) ApplyStatus(ctx context.Context, networkPolicy *applyconfigurationsextensionsv1beta1.NetworkPolicyApplyConfiguration, opts apismetav1.ApplyOptions) (result *apiextensionsv1beta1.NetworkPolicy, err error) {
	if networkPolicy == nil {
		return nil, fmt.Errorf("networkPolicy provided to Apply must not be nil")
	}
	data, err := json.Marshal(networkPolicy)
	if err != nil {
		return nil, err
	}
	name := networkPolicy.Name
	if name == nil {
		return nil, fmt.Errorf("networkPolicy.Name must be provided to Apply")
	}
	obj, err := c.Fake.
		Invokes(clientgotesting.NewPatchSubresourceAction(networkpoliciesResource, c.ns, *name, apimachinerypkgtypes.ApplyPatchType, data, "status"), &apiextensionsv1beta1.NetworkPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*apiextensionsv1beta1.NetworkPolicy), err
}
