//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by conversion-gen. DO NOT EDIT.

package v1beta1

import (
	"unsafe"

	apiauthenticationv1beta1 "k8s.io/api/authentication/v1beta1"
	apimachinerypkgconversion "k8s.io/apimachinery/pkg/conversion"
	apimachinerypkgruntime "k8s.io/apimachinery/pkg/runtime"
	pkgapisauthentication "k8s.io/kubernetes/pkg/apis/authentication"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *apimachinerypkgruntime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*apiauthenticationv1beta1.TokenReview)(nil), (*pkgapisauthentication.TokenReview)(nil), func(a, b interface{}, scope apimachinerypkgconversion.Scope) error {
		return Convert_v1beta1_TokenReview_To_authentication_TokenReview(a.(*apiauthenticationv1beta1.TokenReview), b.(*pkgapisauthentication.TokenReview), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*pkgapisauthentication.TokenReview)(nil), (*apiauthenticationv1beta1.TokenReview)(nil), func(a, b interface{}, scope apimachinerypkgconversion.Scope) error {
		return Convert_authentication_TokenReview_To_v1beta1_TokenReview(a.(*pkgapisauthentication.TokenReview), b.(*apiauthenticationv1beta1.TokenReview), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*apiauthenticationv1beta1.TokenReviewSpec)(nil), (*pkgapisauthentication.TokenReviewSpec)(nil), func(a, b interface{}, scope apimachinerypkgconversion.Scope) error {
		return Convert_v1beta1_TokenReviewSpec_To_authentication_TokenReviewSpec(a.(*apiauthenticationv1beta1.TokenReviewSpec), b.(*pkgapisauthentication.TokenReviewSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*pkgapisauthentication.TokenReviewSpec)(nil), (*apiauthenticationv1beta1.TokenReviewSpec)(nil), func(a, b interface{}, scope apimachinerypkgconversion.Scope) error {
		return Convert_authentication_TokenReviewSpec_To_v1beta1_TokenReviewSpec(a.(*pkgapisauthentication.TokenReviewSpec), b.(*apiauthenticationv1beta1.TokenReviewSpec), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*apiauthenticationv1beta1.TokenReviewStatus)(nil), (*pkgapisauthentication.TokenReviewStatus)(nil), func(a, b interface{}, scope apimachinerypkgconversion.Scope) error {
		return Convert_v1beta1_TokenReviewStatus_To_authentication_TokenReviewStatus(a.(*apiauthenticationv1beta1.TokenReviewStatus), b.(*pkgapisauthentication.TokenReviewStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*pkgapisauthentication.TokenReviewStatus)(nil), (*apiauthenticationv1beta1.TokenReviewStatus)(nil), func(a, b interface{}, scope apimachinerypkgconversion.Scope) error {
		return Convert_authentication_TokenReviewStatus_To_v1beta1_TokenReviewStatus(a.(*pkgapisauthentication.TokenReviewStatus), b.(*apiauthenticationv1beta1.TokenReviewStatus), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*apiauthenticationv1beta1.UserInfo)(nil), (*pkgapisauthentication.UserInfo)(nil), func(a, b interface{}, scope apimachinerypkgconversion.Scope) error {
		return Convert_v1beta1_UserInfo_To_authentication_UserInfo(a.(*apiauthenticationv1beta1.UserInfo), b.(*pkgapisauthentication.UserInfo), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*pkgapisauthentication.UserInfo)(nil), (*apiauthenticationv1beta1.UserInfo)(nil), func(a, b interface{}, scope apimachinerypkgconversion.Scope) error {
		return Convert_authentication_UserInfo_To_v1beta1_UserInfo(a.(*pkgapisauthentication.UserInfo), b.(*apiauthenticationv1beta1.UserInfo), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1beta1_TokenReview_To_authentication_TokenReview(in *apiauthenticationv1beta1.TokenReview, out *pkgapisauthentication.TokenReview, s apimachinerypkgconversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1beta1_TokenReviewSpec_To_authentication_TokenReviewSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1beta1_TokenReviewStatus_To_authentication_TokenReviewStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1beta1_TokenReview_To_authentication_TokenReview is an autogenerated conversion function.
func Convert_v1beta1_TokenReview_To_authentication_TokenReview(in *apiauthenticationv1beta1.TokenReview, out *pkgapisauthentication.TokenReview, s apimachinerypkgconversion.Scope) error {
	return autoConvert_v1beta1_TokenReview_To_authentication_TokenReview(in, out, s)
}

func autoConvert_authentication_TokenReview_To_v1beta1_TokenReview(in *pkgapisauthentication.TokenReview, out *apiauthenticationv1beta1.TokenReview, s apimachinerypkgconversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_authentication_TokenReviewSpec_To_v1beta1_TokenReviewSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_authentication_TokenReviewStatus_To_v1beta1_TokenReviewStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_authentication_TokenReview_To_v1beta1_TokenReview is an autogenerated conversion function.
func Convert_authentication_TokenReview_To_v1beta1_TokenReview(in *pkgapisauthentication.TokenReview, out *apiauthenticationv1beta1.TokenReview, s apimachinerypkgconversion.Scope) error {
	return autoConvert_authentication_TokenReview_To_v1beta1_TokenReview(in, out, s)
}

func autoConvert_v1beta1_TokenReviewSpec_To_authentication_TokenReviewSpec(in *apiauthenticationv1beta1.TokenReviewSpec, out *pkgapisauthentication.TokenReviewSpec, s apimachinerypkgconversion.Scope) error {
	out.Token = in.Token
	out.Audiences = *(*[]string)(unsafe.Pointer(&in.Audiences))
	return nil
}

// Convert_v1beta1_TokenReviewSpec_To_authentication_TokenReviewSpec is an autogenerated conversion function.
func Convert_v1beta1_TokenReviewSpec_To_authentication_TokenReviewSpec(in *apiauthenticationv1beta1.TokenReviewSpec, out *pkgapisauthentication.TokenReviewSpec, s apimachinerypkgconversion.Scope) error {
	return autoConvert_v1beta1_TokenReviewSpec_To_authentication_TokenReviewSpec(in, out, s)
}

func autoConvert_authentication_TokenReviewSpec_To_v1beta1_TokenReviewSpec(in *pkgapisauthentication.TokenReviewSpec, out *apiauthenticationv1beta1.TokenReviewSpec, s apimachinerypkgconversion.Scope) error {
	out.Token = in.Token
	out.Audiences = *(*[]string)(unsafe.Pointer(&in.Audiences))
	return nil
}

// Convert_authentication_TokenReviewSpec_To_v1beta1_TokenReviewSpec is an autogenerated conversion function.
func Convert_authentication_TokenReviewSpec_To_v1beta1_TokenReviewSpec(in *pkgapisauthentication.TokenReviewSpec, out *apiauthenticationv1beta1.TokenReviewSpec, s apimachinerypkgconversion.Scope) error {
	return autoConvert_authentication_TokenReviewSpec_To_v1beta1_TokenReviewSpec(in, out, s)
}

func autoConvert_v1beta1_TokenReviewStatus_To_authentication_TokenReviewStatus(in *apiauthenticationv1beta1.TokenReviewStatus, out *pkgapisauthentication.TokenReviewStatus, s apimachinerypkgconversion.Scope) error {
	out.Authenticated = in.Authenticated
	if err := Convert_v1beta1_UserInfo_To_authentication_UserInfo(&in.User, &out.User, s); err != nil {
		return err
	}
	out.Audiences = *(*[]string)(unsafe.Pointer(&in.Audiences))
	out.Error = in.Error
	return nil
}

// Convert_v1beta1_TokenReviewStatus_To_authentication_TokenReviewStatus is an autogenerated conversion function.
func Convert_v1beta1_TokenReviewStatus_To_authentication_TokenReviewStatus(in *apiauthenticationv1beta1.TokenReviewStatus, out *pkgapisauthentication.TokenReviewStatus, s apimachinerypkgconversion.Scope) error {
	return autoConvert_v1beta1_TokenReviewStatus_To_authentication_TokenReviewStatus(in, out, s)
}

func autoConvert_authentication_TokenReviewStatus_To_v1beta1_TokenReviewStatus(in *pkgapisauthentication.TokenReviewStatus, out *apiauthenticationv1beta1.TokenReviewStatus, s apimachinerypkgconversion.Scope) error {
	out.Authenticated = in.Authenticated
	if err := Convert_authentication_UserInfo_To_v1beta1_UserInfo(&in.User, &out.User, s); err != nil {
		return err
	}
	out.Audiences = *(*[]string)(unsafe.Pointer(&in.Audiences))
	out.Error = in.Error
	return nil
}

// Convert_authentication_TokenReviewStatus_To_v1beta1_TokenReviewStatus is an autogenerated conversion function.
func Convert_authentication_TokenReviewStatus_To_v1beta1_TokenReviewStatus(in *pkgapisauthentication.TokenReviewStatus, out *apiauthenticationv1beta1.TokenReviewStatus, s apimachinerypkgconversion.Scope) error {
	return autoConvert_authentication_TokenReviewStatus_To_v1beta1_TokenReviewStatus(in, out, s)
}

func autoConvert_v1beta1_UserInfo_To_authentication_UserInfo(in *apiauthenticationv1beta1.UserInfo, out *pkgapisauthentication.UserInfo, s apimachinerypkgconversion.Scope) error {
	out.Username = in.Username
	out.UID = in.UID
	out.Groups = *(*[]string)(unsafe.Pointer(&in.Groups))
	out.Extra = *(*map[string]pkgapisauthentication.ExtraValue)(unsafe.Pointer(&in.Extra))
	return nil
}

// Convert_v1beta1_UserInfo_To_authentication_UserInfo is an autogenerated conversion function.
func Convert_v1beta1_UserInfo_To_authentication_UserInfo(in *apiauthenticationv1beta1.UserInfo, out *pkgapisauthentication.UserInfo, s apimachinerypkgconversion.Scope) error {
	return autoConvert_v1beta1_UserInfo_To_authentication_UserInfo(in, out, s)
}

func autoConvert_authentication_UserInfo_To_v1beta1_UserInfo(in *pkgapisauthentication.UserInfo, out *apiauthenticationv1beta1.UserInfo, s apimachinerypkgconversion.Scope) error {
	out.Username = in.Username
	out.UID = in.UID
	out.Groups = *(*[]string)(unsafe.Pointer(&in.Groups))
	out.Extra = *(*map[string]apiauthenticationv1beta1.ExtraValue)(unsafe.Pointer(&in.Extra))
	return nil
}

// Convert_authentication_UserInfo_To_v1beta1_UserInfo is an autogenerated conversion function.
func Convert_authentication_UserInfo_To_v1beta1_UserInfo(in *pkgapisauthentication.UserInfo, out *apiauthenticationv1beta1.UserInfo, s apimachinerypkgconversion.Scope) error {
	return autoConvert_authentication_UserInfo_To_v1beta1_UserInfo(in, out, s)
}
