/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"
	"encoding/json"
	"fmt"

	apiappsv1beta2 "k8s.io/api/apps/v1beta2"
	apismetav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	apimachinerypkglabels "k8s.io/apimachinery/pkg/labels"
	pkgruntimeschema "k8s.io/apimachinery/pkg/runtime/schema"
	apimachinerypkgtypes "k8s.io/apimachinery/pkg/types"
	apimachinerypkgwatch "k8s.io/apimachinery/pkg/watch"
	applyconfigurationsappsv1beta2 "k8s.io/client-go/applyconfigurations/apps/v1beta2"
	clientgotesting "k8s.io/client-go/testing"
)

// FakeReplicaSets implements ReplicaSetInterface
type FakeReplicaSets struct {
	Fake *FakeAppsV1beta2
	ns   string
}

var replicasetsResource = pkgruntimeschema.GroupVersionResource{Group: "apps", Version: "v1beta2", Resource: "replicasets"}

var replicasetsKind = pkgruntimeschema.GroupVersionKind{Group: "apps", Version: "v1beta2", Kind: "ReplicaSet"}

// Get takes name of the replicaSet, and returns the corresponding replicaSet object, and an error if there is any.
func (c *FakeReplicaSets) Get(ctx context.Context, name string, options apismetav1.GetOptions) (result *apiappsv1beta2.ReplicaSet, err error) {
	obj, err := c.Fake.
		Invokes(clientgotesting.NewGetAction(replicasetsResource, c.ns, name), &apiappsv1beta2.ReplicaSet{})

	if obj == nil {
		return nil, err
	}
	return obj.(*apiappsv1beta2.ReplicaSet), err
}

// List takes label and field selectors, and returns the list of ReplicaSets that match those selectors.
func (c *FakeReplicaSets) List(ctx context.Context, opts apismetav1.ListOptions) (result *apiappsv1beta2.ReplicaSetList, err error) {
	obj, err := c.Fake.
		Invokes(clientgotesting.NewListAction(replicasetsResource, replicasetsKind, c.ns, opts), &apiappsv1beta2.ReplicaSetList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := clientgotesting.ExtractFromListOptions(opts)
	if label == nil {
		label = apimachinerypkglabels.Everything()
	}
	list := &apiappsv1beta2.ReplicaSetList{ListMeta: obj.(*apiappsv1beta2.ReplicaSetList).ListMeta}
	for _, item := range obj.(*apiappsv1beta2.ReplicaSetList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a apimachinerypkgwatch.Interface that watches the requested replicaSets.
func (c *FakeReplicaSets) Watch(ctx context.Context, opts apismetav1.ListOptions) (apimachinerypkgwatch.Interface, error) {
	return c.Fake.
		InvokesWatch(clientgotesting.NewWatchAction(replicasetsResource, c.ns, opts))

}

// Create takes the representation of a replicaSet and creates it.  Returns the server's representation of the replicaSet, and an error, if there is any.
func (c *FakeReplicaSets) Create(ctx context.Context, replicaSet *apiappsv1beta2.ReplicaSet, opts apismetav1.CreateOptions) (result *apiappsv1beta2.ReplicaSet, err error) {
	obj, err := c.Fake.
		Invokes(clientgotesting.NewCreateAction(replicasetsResource, c.ns, replicaSet), &apiappsv1beta2.ReplicaSet{})

	if obj == nil {
		return nil, err
	}
	return obj.(*apiappsv1beta2.ReplicaSet), err
}

// Update takes the representation of a replicaSet and updates it. Returns the server's representation of the replicaSet, and an error, if there is any.
func (c *FakeReplicaSets) Update(ctx context.Context, replicaSet *apiappsv1beta2.ReplicaSet, opts apismetav1.UpdateOptions) (result *apiappsv1beta2.ReplicaSet, err error) {
	obj, err := c.Fake.
		Invokes(clientgotesting.NewUpdateAction(replicasetsResource, c.ns, replicaSet), &apiappsv1beta2.ReplicaSet{})

	if obj == nil {
		return nil, err
	}
	return obj.(*apiappsv1beta2.ReplicaSet), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeReplicaSets) UpdateStatus(ctx context.Context, replicaSet *apiappsv1beta2.ReplicaSet, opts apismetav1.UpdateOptions) (*apiappsv1beta2.ReplicaSet, error) {
	obj, err := c.Fake.
		Invokes(clientgotesting.NewUpdateSubresourceAction(replicasetsResource, "status", c.ns, replicaSet), &apiappsv1beta2.ReplicaSet{})

	if obj == nil {
		return nil, err
	}
	return obj.(*apiappsv1beta2.ReplicaSet), err
}

// Delete takes name of the replicaSet and deletes it. Returns an error if one occurs.
func (c *FakeReplicaSets) Delete(ctx context.Context, name string, opts apismetav1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(clientgotesting.NewDeleteActionWithOptions(replicasetsResource, c.ns, name, opts), &apiappsv1beta2.ReplicaSet{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeReplicaSets) DeleteCollection(ctx context.Context, opts apismetav1.DeleteOptions, listOpts apismetav1.ListOptions) error {
	action := clientgotesting.NewDeleteCollectionAction(replicasetsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &apiappsv1beta2.ReplicaSetList{})
	return err
}

// Patch applies the patch and returns the patched replicaSet.
func (c *FakeReplicaSets) Patch(ctx context.Context, name string, pt apimachinerypkgtypes.PatchType, data []byte, opts apismetav1.PatchOptions, subresources ...string) (result *apiappsv1beta2.ReplicaSet, err error) {
	obj, err := c.Fake.
		Invokes(clientgotesting.NewPatchSubresourceAction(replicasetsResource, c.ns, name, pt, data, subresources...), &apiappsv1beta2.ReplicaSet{})

	if obj == nil {
		return nil, err
	}
	return obj.(*apiappsv1beta2.ReplicaSet), err
}

// Apply takes the given apply declarative configuration, applies it and returns the applied replicaSet.
func (c *FakeReplicaSets) Apply(ctx context.Context, replicaSet *applyconfigurationsappsv1beta2.ReplicaSetApplyConfiguration, opts apismetav1.ApplyOptions) (result *apiappsv1beta2.ReplicaSet, err error) {
	if replicaSet == nil {
		return nil, fmt.Errorf("replicaSet provided to Apply must not be nil")
	}
	data, err := json.Marshal(replicaSet)
	if err != nil {
		return nil, err
	}
	name := replicaSet.Name
	if name == nil {
		return nil, fmt.Errorf("replicaSet.Name must be provided to Apply")
	}
	obj, err := c.Fake.
		Invokes(clientgotesting.NewPatchSubresourceAction(replicasetsResource, c.ns, *name, apimachinerypkgtypes.ApplyPatchType, data), &apiappsv1beta2.ReplicaSet{})

	if obj == nil {
		return nil, err
	}
	return obj.(*apiappsv1beta2.ReplicaSet), err
}

// ApplyStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
func (c *FakeReplicaSets) ApplyStatus(ctx context.Context, replicaSet *applyconfigurationsappsv1beta2.ReplicaSetApplyConfiguration, opts apismetav1.ApplyOptions) (result *apiappsv1beta2.ReplicaSet, err error) {
	if replicaSet == nil {
		return nil, fmt.Errorf("replicaSet provided to Apply must not be nil")
	}
	data, err := json.Marshal(replicaSet)
	if err != nil {
		return nil, err
	}
	name := replicaSet.Name
	if name == nil {
		return nil, fmt.Errorf("replicaSet.Name must be provided to Apply")
	}
	obj, err := c.Fake.
		Invokes(clientgotesting.NewPatchSubresourceAction(replicasetsResource, c.ns, *name, apimachinerypkgtypes.ApplyPatchType, data, "status"), &apiappsv1beta2.ReplicaSet{})

	if obj == nil {
		return nil, err
	}
	return obj.(*apiappsv1beta2.ReplicaSet), err
}
